project_id = "jzsuwnonmfmdtiodepzk"

[functions.ai-assistant]
verify_jwt = false

[functions.create-barber]
verify_jwt = true

[functions.telegram-webhook]
verify_jwt = false

[functions.notify-booking]
verify_jwt = false
